global:

    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'

scrape_configs:

    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
          
    - job_name: 'redis_exporter_targets'
      static_configs:
        - targets:
          - treegateway-config-redis-dev.1aavrl.0001.use1.cache.amazonaws.com:6379
      metrics_path: /scrape
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: dev-gateway.verity.com.br:9121
          
    - job_name: 'treegateway'
      static_configs:
          - targets:
            - dev-gateway.verity.com.br:2001

    - job_name: 'node-exporter'
      ec2_sd_configs:
        - region: 'us-east-1'
          access_key: AKIAQNSVONHVL3CRIB73
          secret_key: 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
          port: 9100

      relabel_configs:
        - source_labels: [__meta_ec2_private_ip]
          target_label: 'private_ip'

        - source_labels: [__meta_ec2_public_ip]
          regex:  '(.*)'
          target_label: __address__
          replacement: '${1}:9100'

        - source_labels: [__meta_ec2_instance_state]
          target_label: 'instance_state'

    - job_name: 'cadvisor'
      ec2_sd_configs:
        - region: 'us-east-1'
          access_key: AKIAQNSVONHVL3CRIB73
          secret_key: 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
          port: 9200

      relabel_configs:
        - source_labels: [__meta_ec2_private_ip]
          target_label: 'private_ip'

        - source_labels: [__meta_ec2_public_ip]
          regex:  '(.*)'
          target_label: __address__
          replacement: '${1}:9200'

        - source_labels: [__meta_ec2_instance_state]
          target_label: 'instance_state'
