global:

    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'

scrape_configs:

    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
          
    - job_name: 'treegateway'
      static_configs:
          - targets:
            - tree-gateway:8000
            - dev-gateway.verity.com.br:8000
            - tree-gateway:2001
            - dev-gateway.verity.com.br:2001
            - 3.222.61.138:2001

    - job_name: 'node-exporter'
      ec2_sd_configs:
        - region: 'us-east-1'
          access_key: AKIAQNSVONHVL3CRIB73
          secret_key: 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
          port: 9100

      relabel_configs:
        - source_labels: [__meta_ec2_private_ip]
          target_label: 'private_ip'

        - source_labels: [__meta_ec2_public_ip]
          regex:  '(.*)'
          target_label: __address__
          replacement: '${1}:9100'

        - source_labels: [__meta_ec2_instance_state]
          target_label: 'instance_state'

    - job_name: 'cadvisor'
      ec2_sd_configs:
        - region: 'us-east-1'
          access_key: AKIAQNSVONHVL3CRIB73
          secret_key: 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
          port: 9200

      relabel_configs:
        - source_labels: [__meta_ec2_private_ip]
          target_label: 'private_ip'

        - source_labels: [__meta_ec2_public_ip]
          regex:  '(.*)'
          target_label: __address__
          replacement: '${1}:9200'

        - source_labels: [__meta_ec2_instance_state]
          target_label: 'instance_state'
