global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'ecs_node_exporter'
    ec2_sd_configs:
      - region: us-east-1
      port: 9100 # referred to nodeExporter exposed port
      role_arn: arn:aws:iam::029170231786:role/prometheus_ec2_readonly
      
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - region: us-east-1
      port: 9200 # referred to cAdvisor exposed port
      role_arn: arn:aws:iam::029170231786:role/prometheus_ec2_readonly
      